# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-17 17:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='rssdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(blank=True, max_length=100)),
                ('body', models.TextField()),
                ('death', models.CharField(blank=True, max_length=100)),
                ('death_no', models.IntegerField(blank=True, null=True)),
                ('injury', models.CharField(blank=True, max_length=100)),
                ('injury_no', models.IntegerField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('vehicle_no', models.CharField(blank=True, max_length=100)),
                ('date', models.DateField(default=datetime.date.today)),
                ('day', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-date', 'location'),
                'verbose_name': 'rssdata',
            },
        ),
    ]
