# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-24 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_extraction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rssdata',
            name='day',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rssdata',
            name='death',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rssdata',
            name='injury',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rssdata',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rssdata',
            name='vehicle_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
