# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-05 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_extraction', '0003_auto_20180524_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='rssdata',
            name='vehicle_involved',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
