# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-05 14:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news_extraction', '0004_rssdata_vehicle_involved'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='vehicle',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news_extraction.Vehicle_category'),
        ),
    ]
