# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-06 14:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_extraction', '0005_auto_20180605_2018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='category',
        ),
        migrations.DeleteModel(
            name='Vehicle',
        ),
        migrations.DeleteModel(
            name='Vehicle_category',
        ),
    ]
