# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-14 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_extraction', '0006_auto_20180606_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='rssdata',
            name='month',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rssdata',
            name='season',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rssdata',
            name='year',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
