# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-14 13:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_extraction', '0007_auto_20180614_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rssdata',
            name='date',
            field=models.CharField(blank=True, default=datetime.date.today, max_length=100, null=True),
        ),
    ]
