# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-15 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_extraction', '0008_auto_20180614_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rssdata',
            name='location',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
