# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-17 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_extraction', '0009_auto_20180615_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='rssdata',
            name='link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
