# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-18 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_extraction', '0010_rssdata_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='rssdata',
            name='district',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
