# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-18 17:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_extraction', '0011_rssdata_district'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rssdata',
            name='district',
        ),
    ]
