# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-24 09:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news_extraction', '0013_auto_20180624_1515'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicledetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_no', models.CharField(blank=True, max_length=100, null=True)),
                ('vehicle_type', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='rssdata',
            name='vehicle_no',
        ),
        migrations.AddField(
            model_name='vehicledetail',
            name='post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='news_extraction.rssdata'),
        ),
    ]
