# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-24 13:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news_extraction', '0014_auto_20180624_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datedetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(blank=True, max_length=100, null=True)),
                ('season', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.CharField(blank=True, max_length=100, null=True)),
                ('day', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='rssdata',
            name='day',
        ),
        migrations.RemoveField(
            model_name='rssdata',
            name='month',
        ),
        migrations.RemoveField(
            model_name='rssdata',
            name='season',
        ),
        migrations.RemoveField(
            model_name='rssdata',
            name='year',
        ),
        migrations.AddField(
            model_name='datedetail',
            name='post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='news_extraction.rssdata'),
        ),
    ]
