# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-24 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_extraction', '0015_auto_20180624_1858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datedetail',
            name='post',
        ),
        migrations.RemoveField(
            model_name='vehicledetail',
            name='post',
        ),
        migrations.AddField(
            model_name='rssdata',
            name='day',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rssdata',
            name='month',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rssdata',
            name='season',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rssdata',
            name='vehicle_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rssdata',
            name='vehicle_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rssdata',
            name='year',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Datedetail',
        ),
        migrations.DeleteModel(
            name='Vehicledetail',
        ),
    ]
