# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-25 14:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_extraction', '0016_auto_20180624_2210'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rssdata',
            options={'ordering': ('-date', 'location', 'vehicle_involved'), 'verbose_name': 'rssdata'},
        ),
    ]
