# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-25 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_extraction', '0017_auto_20180625_2027'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rssdata',
            options={'ordering': ('-date', 'location', 'vehicleone', 'vehicletwo'), 'verbose_name': 'rssdata'},
        ),
        migrations.RenameField(
            model_name='rssdata',
            old_name='vehicle_involved',
            new_name='vehicleone',
        ),
        migrations.AddField(
            model_name='rssdata',
            name='vehicletwo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
