# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-23 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_extraction', '0018_auto_20180625_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='rssdata',
            name='cause',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='rssdata',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
