# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-28 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='Death',
            field=models.CharField(default=0, max_length=120),
        ),
        migrations.AlterField(
            model_name='news',
            name='Injury',
            field=models.CharField(default=0, max_length=120),
        ),
        migrations.AlterField(
            model_name='news',
            name='Year',
            field=models.CharField(default=None, max_length=120),
        ),
    ]
