# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-15 15:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0003_rssdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='rssdata',
        ),
    ]
