# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-23 06:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0004_delete_rssdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
    ]
